sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - DB=mysql TYPO3=coreapi/develop INTEGRATION=master COVERAGE=0

matrix:
  allow_failures:
    - php: hhvm

services:
  - memcached
  - redis-server

addons:
  apt:
    packages:
      # Get latest git version cause of travis issues (https://github.com/travis-ci/travis-ci/issues/1710)
      - git
      - parallel
      - tree

notifications:
  email:
    - blueduck@gmx.net
  slack:
    rooms:
      - typo3:DHkQdCNWc6x2znPAYA5T2LXO#gsoc-coreapi

before_script:
  - >
    if [[ "$TRAVIS_PHP_VERSION" = "5.3" || "$TRAVIS_PHP_VERSION" = "5.4" ]]; then
        echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
        echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
        echo "apc.slam_defense=0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
        pecl install igbinary > /dev/null;
    fi
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd ..
  - git clone --single-branch --branch $INTEGRATION --depth 1 git://github.com/TYPO3-coreapi/TYPO3-Travis-Integration.git build-environment
  - source build-environment/install-helper.sh
  - git clone --single-branch --branch $TYPO3 --depth 1 https://github.com/TYPO3-coreapi/TYPO3CMS.git core
  - mv core/* .
  - composer self-update
  - composer --dev install
  - mkdir -p fileadmin uploads typo3temp typo3conf/ext/
  - mv ext-coreapi typo3conf/ext/coreapi

script:
 - phpLint typo3conf/ext/coreapi
 - >
    echo;
    echo "Running unit tests";
    ./bin/phpunit --colors --coverage-clover=coverage.clover -c typo3/sysext/core/Build/UnitTests.xml typo3conf/ext/coreapi/Tests/Unit/
 - wget https://scrutinizer-ci.com/ocular.phar
 - cp -R typo3conf/ext/coreapi/.git .
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover